import sys
sys.path.append(".")

from datetime import datetime
from scrapers.yahoo_scraper import get_stock_data
from scrapers.edgar_scraper import get_recent_filings, get_filing_text, clean_filing_text
from scrapers.news_scraper import get_company_news
from agents.risk_agent import analyze_risks
from agents.valuation_agent import analyze_valuation
from agents.news_agent import analyze_news_sentiment


def generate_report(ticker, company_name):
    print(f"\n{'='*50}")
    print(f"Generating report for {ticker}")
    print(f"{'='*50}\n")

    # Step 1: Stock data
    print("[1/5] Fetching stock data...")
    stock_data = get_stock_data(ticker)

    # Step 2: 10-K filing
    print("[2/5] Fetching 10-K filing...")
    filings = get_recent_filings(ticker, filing_type="10-K", count=1)
    filing_text = ""
    if filings:
        raw_text = get_filing_text(ticker, filings[0]["accession_number"], filings[0]["primary_document"])
        filing_text = clean_filing_text(raw_text)

    # Step 3: News
    print("[3/5] Fetching news...")
    articles = get_company_news(company_name, ticker, count=8)

    # Step 4: Run all agents
    print("[4/5] Running AI agents (this may take 30-60 seconds)...")
    risk_summary = analyze_risks(filing_text, ticker) if filing_text else "No filing data available."
    valuation_summary = analyze_valuation(stock_data, ticker)
    news_summary = analyze_news_sentiment(articles, ticker)

    # Step 5: Assemble markdown report
    print("[5/5] Assembling report...")
    report = f"""# Equity Research Report: {stock_data.get('company_name', ticker)} ({ticker})
*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}*

## Company Overview
- **Sector:** {stock_data.get('sector', 'N/A')}
- **Current Price:** ${stock_data.get('current_price', 'N/A')}
- **Market Cap:** ${stock_data.get('market_cap', 'N/A')}
- **P/E Ratio:** {stock_data.get('pe_ratio', 'N/A')}
- **EPS:** ${stock_data.get('eps', 'N/A')}
- **52-Week Range:** ${stock_data.get('52_week_low', 'N/A')} - ${stock_data.get('52_week_high', 'N/A')}

## Valuation Analysis
{valuation_summary}

## Risk Factors
{risk_summary}

## News & Sentiment
{news_summary}

---
*This report was generated by an AI-powered research system. It is not financial advice.*
"""

    # Save to file
    filename = f"data/{ticker}_report.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\nReport saved to {filename}")
    return report


if __name__ == "__main__":
    ticker = input("Enter ticker: ")
    company_name = input("Enter company name (e.g. Apple Inc): ")
    report = generate_report(ticker, company_name)
    print("\n" + "="*50)
    print(report)